apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "myapp.fullname" . }}-job
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: http-echo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.image.args }}
        args: {{ .Values.image.args | toJson }}
        {{- end }}
        ports:
        - containerPort: 5200
